// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi3slyslR28rzd_X2yMZHmQ8rkWNEH-K8',
    appId: '1:973420783204:web:a4388727bd14936d2b6171',
    messagingSenderId: '973420783204',
    projectId: 'cloudfirestore-utrack-api',
    authDomain: 'cloudfirestore-utrack-api.firebaseapp.com',
    storageBucket: 'cloudfirestore-utrack-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS6OGhOkZlKZwsB6K2Er0MzYc7wJ1iuxo',
    appId: '1:973420783204:android:4fb19d0e5fffca662b6171',
    messagingSenderId: '973420783204',
    projectId: 'cloudfirestore-utrack-api',
    storageBucket: 'cloudfirestore-utrack-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVI7IJPBm3AijhJyOqFEfXTFp-ERK16ac',
    appId: '1:973420783204:ios:ff7a781dc5dff4232b6171',
    messagingSenderId: '973420783204',
    projectId: 'cloudfirestore-utrack-api',
    storageBucket: 'cloudfirestore-utrack-api.appspot.com',
    iosClientId: '973420783204-0dcc1si009lacsss366honcvnhrnpuhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
